name: Heatmap
version: '${version}'
main: dev.arctic.heatmap.Heatmap
api-version: '1.20'
load: POSTWORLD
libraries:
  - 'com.h2database:h2:2.2.224'
depend: [WorldGuard]
commands:
  heatmap:
    description: Primary command for plugin!